lista = [1,2]
a = lista.append(3)
lista.append(4)
print(lista)
lista.append([4,5])
print(lista)
print(a)
print(lista.count(4)+lista[-1].count(4))
lista.extend([1,2,3,1,2,3,4])
print(lista)
l2=[1,2,3,1,2,3,4]
lista.extend((l2))
print(lista)

print('******************************************************')

print(lista.index(4))
procura=int(input("Qual o numero a procurar?"))
print(lista.count(procura))
lista.insert(3,'dois')
print(lista)
b = lista.pop(3)
print(b)
print(lista)
c = lista.remove(4)
print(lista)
print(c)
lista.remove([4,5])
print(lista)
print('******************************************************')
lista.reverse()
print(lista)
lista.reverse()
print(lista)
